insert into fit_user (username, password, email, premium, active, pt, fit_user_id)
values (1,comrad,russia,viktor@kgb.com,1,1,0,-1)
insert into fit_user (username, password, email, premium, active, pt, fit_user_id)
values (2,comrad2,russia,viktor2@kgb.com,1,1,1,-1)
insert into fit_user (username, password, email, premium, active, pt, fit_user_id)
values (3,comrad3,russia,viktor3@kgb.com,1,1,0,2)