-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-04-16 18:40:10 BST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activities_template (
    act_id         INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    name           VARCHAR2(64) NOT NULL,
    cal_step_mult  NUMBER(5, 2),
    cal_dist_mutl  NUMBER(5, 2),
    cal_time_mult  NUMBER(5, 2)
)
LOGGING;

ALTER TABLE activities_template ADD CONSTRAINT activities_template_pk PRIMARY KEY ( act_id );

CREATE TABLE daily_goals (
    fit_user_id  INTEGER NOT NULL,
    daily_steps  NUMBER(7, 2) DEFAULT 0,
    daily_cals   NUMBER(7, 2) DEFAULT 0
)
LOGGING;

ALTER TABLE daily_goals ADD CONSTRAINT daily_goals_pk PRIMARY KEY ( fit_user_id );

CREATE TABLE daily_status (
    daily_id     INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    distance     NUMBER(7, 2) NOT NULL,
    steps        NUMBER(7, 2) NOT NULL,
    weigth       NUMBER(5, 2) NOT NULL,
    calories     NUMBER(7, 2) NOT NULL,
    completed    NUMBER(1) DEFAULT 0
)
LOGGING;

ALTER TABLE daily_status ADD CONSTRAINT daily_status_pk PRIMARY KEY ( daily_id );

CREATE TABLE exercises (
    ex_id                       INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    activities_template_act_id  INTEGER NOT NULL,
    fit_user_id                 INTEGER NOT NULL,
    duration                    DATE,
    steps                       NUMBER(7, 2),
    distance                    NUMBER(7, 2),
    calories                    NUMBER(7, 2),
    begin_date                  TIMESTAMP WITH LOCAL TIME ZONE,
    end_date                    TIMESTAMP WITH LOCAL TIME ZONE
)
LOGGING;

ALTER TABLE exercises ADD CONSTRAINT exercises_pk PRIMARY KEY ( ex_id );

CREATE TABLE fit_user (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    username     VARCHAR2(64) NOT NULL,
    password     VARCHAR2(64) NOT NULL,
    email        VARCHAR2(128) NOT NULL,
    premium      NUMBER,
    active       NUMBER,
    pt           NUMBER,
    fit_user_id  INTEGER NOT NULL
)
LOGGING;

CREATE UNIQUE INDEX fit_user__idx ON
    fit_user (
        fit_user_id
    ASC )
        LOGGING;

ALTER TABLE fit_user ADD CONSTRAINT user_pk PRIMARY KEY ( id );

CREATE TABLE friends_leaderboard (
    leader_id    INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    name         VARCHAR2(128),
    place        NUMBER(7),
    exercise     VARCHAR2(64),
    value        NUMBER(7, 2)
)
LOGGING;

ALTER TABLE friends_leaderboard ADD CONSTRAINT friends_leaderboard_pk PRIMARY KEY ( leader_id );

CREATE TABLE friends_list (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    friends_id   INTEGER NOT NULL
)
LOGGING;

ALTER TABLE friends_list ADD CONSTRAINT friends_list_pk PRIMARY KEY ( id );

CREATE TABLE notice (
    n_id             INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    exercises_ex_id  INTEGER NOT NULL,
    fit_user_id      INTEGER NOT NULL,
    date_hour        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    title            VARCHAR2(64) NOT NULL,
    description      VARCHAR2(128) NOT NULL,
    brief            VARCHAR2(64) NOT NULL
)
LOGGING;

ALTER TABLE notice ADD CONSTRAINT notice_pk PRIMARY KEY ( n_id );

CREATE TABLE profile (
    fit_user_id  INTEGER NOT NULL,
    name         VARCHAR2(128) NOT NULL,
    weight       NUMBER(5, 2),
    height       NUMBER(5, 2),
    bday         DATE NOT NULL,
    gender       VARCHAR2(64)
)
LOGGING;

ALTER TABLE profile ADD CONSTRAINT profile_pk PRIMARY KEY ( fit_user_id );

CREATE TABLE totals (
    fit_user_id                 INTEGER NOT NULL,
    activities_template_act_id  INTEGER NOT NULL,
    distance                    NUMBER(7, 2),
    calories                    NUMBER(7, 2)
)
LOGGING;

ALTER TABLE totals ADD CONSTRAINT totals_pk PRIMARY KEY ( fit_user_id,
                                                          activities_template_act_id );

CREATE TABLE transaction (
    tr_id        INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    value        NUMBER(4, 2) NOT NULL,
    t_date       TIMESTAMP WITH LOCAL TIME ZONE NOT NULL
)
LOGGING;

ALTER TABLE transaction ADD CONSTRAINT transaction_pk PRIMARY KEY ( tr_id );

CREATE TABLE user_activity (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    act_date     DATE,
    begin_date   TIMESTAMP WITH LOCAL TIME ZONE,
    end_date     TIMESTAMP WITH LOCAL TIME ZONE,
    paid         NUMBER(1)
)
LOGGING;

ALTER TABLE user_activity ADD CONSTRAINT user_activity_pk PRIMARY KEY ( id );

ALTER TABLE daily_goals
    ADD CONSTRAINT daily_goals_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE daily_status
    ADD CONSTRAINT daily_status_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE exercises
    ADD CONSTRAINT exercises_act_fk FOREIGN KEY ( activities_template_act_id )
        REFERENCES activities_template ( act_id )
    NOT DEFERRABLE;

ALTER TABLE exercises
    ADD CONSTRAINT exercises_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE fit_user
    ADD CONSTRAINT fit_user_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE friends_leaderboard
    ADD CONSTRAINT fl_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE friends_list
    ADD CONSTRAINT friends_list_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE notice
    ADD CONSTRAINT notice_exercises_fk FOREIGN KEY ( exercises_ex_id )
        REFERENCES exercises ( ex_id )
    NOT DEFERRABLE;

ALTER TABLE notice
    ADD CONSTRAINT notice_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE profile
    ADD CONSTRAINT profile_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE totals
    ADD CONSTRAINT totals_activities_template_fk FOREIGN KEY ( activities_template_act_id )
        REFERENCES activities_template ( act_id )
    NOT DEFERRABLE;

ALTER TABLE totals
    ADD CONSTRAINT totals_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE transaction
    ADD CONSTRAINT transaction_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE user_activity
    ADD CONSTRAINT user_activity_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

CREATE SEQUENCE profile_fit_user_id_seq START WITH 1 NOCACHE ORDER;

CREATE OR REPLACE TRIGGER profile_fit_user_id_trg BEFORE
    INSERT ON profile
    FOR EACH ROW
    WHEN ( new.fit_user_id IS NULL )
BEGIN
    :new.fit_user_id := profile_fit_user_id_seq.nextval;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
