/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessapp;
import java.util.Arrays;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import org.json.JSONObject;
import org.json.JSONArray;
/**
 *
 * @author Dell
 */
public class Application extends javax.swing.JFrame {
    public FitnessApp fitapp;
    public boolean logedIn = false;
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NewGoalsPopUp = new javax.swing.JDialog();
        newStepsGoals = new javax.swing.JTextField();
        newCaloriesGoals = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setNewGoalsOkButton = new javax.swing.JButton();
        NewFriendPopUp = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        NewFriendName = new javax.swing.JTextField();
        OkAddFriendButton = new javax.swing.JButton();
        errorNewFriendAdd = new javax.swing.JLabel();
        mainWindow = new javax.swing.JTabbedPane();
        LogRegTab = new javax.swing.JTabbedPane();
        loginTab = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logInButton = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        registerTab = new javax.swing.JPanel();
        homeScreenTab = new javax.swing.JScrollPane();
        homeScreen = new javax.swing.JPanel();
        addExerciseButton = new javax.swing.JButton();
        friendsButton = new javax.swing.JButton();
        userIcon = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        stepsFrame = new javax.swing.JInternalFrame();
        stepsText = new javax.swing.JLabel();
        stepsNumber = new javax.swing.JLabel();
        dailyStepsProgressBar = new javax.swing.JProgressBar();
        percentageText = new javax.swing.JLabel();
        setNewGoalsButton = new javax.swing.JButton();
        weightFrame = new javax.swing.JInternalFrame();
        weightText = new javax.swing.JLabel();
        weightNumber = new javax.swing.JLabel();
        lastExerciseFrame = new javax.swing.JInternalFrame();
        lastExerciseText = new javax.swing.JLabel();
        distanceNumber = new javax.swing.JLabel();
        durationNumber = new javax.swing.JLabel();
        caloriesNumber = new javax.swing.JLabel();
        exerciseDateText = new javax.swing.JLabel();
        friendsListTab = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendsListTable = new javax.swing.JTable();
        addFriendButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        friendsRequestTable = new javax.swing.JTable();

        NewGoalsPopUp.setTitle("Define New Goals");
        NewGoalsPopUp.setMinimumSize(new java.awt.Dimension(460, 260));
        NewGoalsPopUp.setPreferredSize(new java.awt.Dimension(480, 300));
        NewGoalsPopUp.setSize(new java.awt.Dimension(480, 300));

        newStepsGoals.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        newCaloriesGoals.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("New Steps");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("New Calories");

        setNewGoalsOkButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setNewGoalsOkButton.setText("OK");
        setNewGoalsOkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNewGoalsOkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout NewGoalsPopUpLayout = new javax.swing.GroupLayout(NewGoalsPopUp.getContentPane());
        NewGoalsPopUp.getContentPane().setLayout(NewGoalsPopUpLayout);
        NewGoalsPopUpLayout.setHorizontalGroup(
            NewGoalsPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGoalsPopUpLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(NewGoalsPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(setNewGoalsOkButton)
                    .addGroup(NewGoalsPopUpLayout.createSequentialGroup()
                        .addComponent(newStepsGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(newCaloriesGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NewGoalsPopUpLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201)
                        .addComponent(jLabel2)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        NewGoalsPopUpLayout.setVerticalGroup(
            NewGoalsPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewGoalsPopUpLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(NewGoalsPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(NewGoalsPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newStepsGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCaloriesGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(setNewGoalsOkButton)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        NewFriendPopUp.setTitle("New Friend");
        NewFriendPopUp.setMinimumSize(new java.awt.Dimension(480, 300));
        NewFriendPopUp.setPreferredSize(new java.awt.Dimension(480, 300));
        NewFriendPopUp.setSize(new java.awt.Dimension(480, 300));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Friend's Name");
        jLabel6.setToolTipText("");

        NewFriendName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        OkAddFriendButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OkAddFriendButton.setText("ADD");
        OkAddFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkAddFriendButtonActionPerformed(evt);
            }
        });

        errorNewFriendAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout NewFriendPopUpLayout = new javax.swing.GroupLayout(NewFriendPopUp.getContentPane());
        NewFriendPopUp.getContentPane().setLayout(NewFriendPopUpLayout);
        NewFriendPopUpLayout.setHorizontalGroup(
            NewFriendPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewFriendPopUpLayout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addGroup(NewFriendPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewFriendName, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OkAddFriendButton)
                    .addComponent(errorNewFriendAdd))
                .addGap(165, 165, 165))
        );
        NewFriendPopUpLayout.setVerticalGroup(
            NewFriendPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewFriendPopUpLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NewFriendName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(OkAddFriendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(errorNewFriendAdd)
                .addGap(42, 42, 42))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FitnessApp");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setSize(new java.awt.Dimension(1280, 720));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOGIN");

        usernameLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameLabelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setText("username:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("password:");

        logInButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logInButton.setText("OK");
        logInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInButtonActionPerformed(evt);
            }
        });

        errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout loginTabLayout = new javax.swing.GroupLayout(loginTab);
        loginTab.setLayout(loginTabLayout);
        loginTabLayout.setHorizontalGroup(
            loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(logInButton)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(loginTabLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addGroup(loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .addComponent(usernameLabel))
                .addContainerGap(500, Short.MAX_VALUE))
        );
        loginTabLayout.setVerticalGroup(
            loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginTabLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loginTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logInButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(errorLabel)
                .addContainerGap(537, Short.MAX_VALUE))
        );

        LogRegTab.addTab("Login", loginTab);

        javax.swing.GroupLayout registerTabLayout = new javax.swing.GroupLayout(registerTab);
        registerTab.setLayout(registerTabLayout);
        registerTabLayout.setHorizontalGroup(
            registerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        registerTabLayout.setVerticalGroup(
            registerTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 974, Short.MAX_VALUE)
        );

        LogRegTab.addTab("Register", registerTab);

        mainWindow.addTab("Login and Register", LogRegTab);

        homeScreenTab.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        homeScreenTab.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        homeScreenTab.getVerticalScrollBar().setUnitIncrement(20);
        homeScreenTab.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                homeScreenTabFocusGained(evt);
            }
        });
        homeScreenTab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                homeScreenTabComponentShown(evt);
            }
        });

        addExerciseButton.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addExerciseButton.setText("+");
        addExerciseButton.setAlignmentX(0.5F);
        addExerciseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addExerciseButton.setFocusable(false);
        addExerciseButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addExerciseButton.setMaximumSize(new java.awt.Dimension(60, 60));
        addExerciseButton.setMinimumSize(new java.awt.Dimension(60, 60));
        addExerciseButton.setName(""); // NOI18N
        addExerciseButton.setPreferredSize(new java.awt.Dimension(60, 60));
        addExerciseButton.setSelected(true);
        addExerciseButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        addExerciseButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addExerciseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExerciseButtonActionPerformed(evt);
            }
        });

        friendsButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        friendsButton.setText("Friends");
        friendsButton.setFocusable(false);

        userIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userIcon.setText("[ICON]");
        userIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        userIcon.setMaximumSize(new java.awt.Dimension(205, 220));
        userIcon.setMinimumSize(new java.awt.Dimension(205, 220));
        userIcon.setName(""); // NOI18N
        userIcon.setPreferredSize(new java.awt.Dimension(205, 220));
        userIcon.setVerifyInputWhenFocusTarget(false);

        userName.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("NAME");

        stepsFrame.setVisible(true);

        stepsText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stepsText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepsText.setText("Steps:");

        stepsNumber.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        stepsNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stepsNumber.setText("12345");

        dailyStepsProgressBar.setValue(10);

        percentageText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        percentageText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        percentageText.setText("10% out of 9999 steps");

        setNewGoalsButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        setNewGoalsButton.setText("Set New Goals");
        setNewGoalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setNewGoalsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stepsFrameLayout = new javax.swing.GroupLayout(stepsFrame.getContentPane());
        stepsFrame.getContentPane().setLayout(stepsFrameLayout);
        stepsFrameLayout.setHorizontalGroup(
            stepsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stepsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(dailyStepsProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsText)
                    .addComponent(percentageText)
                    .addComponent(setNewGoalsButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stepsFrameLayout.setVerticalGroup(
            stepsFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stepsFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stepsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepsNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dailyStepsProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(percentageText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(setNewGoalsButton)
                .addContainerGap())
        );

        weightFrame.setVisible(true);

        weightText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        weightText.setText("Weight (kg): ");

        weightNumber.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        weightNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        weightNumber.setText("12345");

        javax.swing.GroupLayout weightFrameLayout = new javax.swing.GroupLayout(weightFrame.getContentPane());
        weightFrame.getContentPane().setLayout(weightFrameLayout);
        weightFrameLayout.setHorizontalGroup(
            weightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightFrameLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(weightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(weightNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weightText))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        weightFrameLayout.setVerticalGroup(
            weightFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weightFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(weightText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weightNumber)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lastExerciseFrame.setVisible(true);

        lastExerciseText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lastExerciseText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lastExerciseText.setText("Last Exercise:");

        distanceNumber.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        distanceNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        durationNumber.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        durationNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        caloriesNumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        caloriesNumber.setToolTipText("");

        exerciseDateText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exerciseDateText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout lastExerciseFrameLayout = new javax.swing.GroupLayout(lastExerciseFrame.getContentPane());
        lastExerciseFrame.getContentPane().setLayout(lastExerciseFrameLayout);
        lastExerciseFrameLayout.setHorizontalGroup(
            lastExerciseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastExerciseFrameLayout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addGroup(lastExerciseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lastExerciseText)
                    .addComponent(caloriesNumber)
                    .addComponent(exerciseDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lastExerciseFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(durationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(distanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        lastExerciseFrameLayout.setVerticalGroup(
            lastExerciseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lastExerciseFrameLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lastExerciseText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(lastExerciseFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caloriesNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(exerciseDateText)
                .addContainerGap())
        );

        javax.swing.GroupLayout homeScreenLayout = new javax.swing.GroupLayout(homeScreen);
        homeScreen.setLayout(homeScreenLayout);
        homeScreenLayout.setHorizontalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(friendsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186)
                .addGroup(homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(weightFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lastExerciseFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(240, 240, 240)
                .addComponent(addExerciseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        homeScreenLayout.setVerticalGroup(
            homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(homeScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addExerciseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(friendsButton)))
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stepsFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(weightFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lastExerciseFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        addExerciseButton.getAccessibleContext().setAccessibleName("addExerciseButton");
        userIcon.getAccessibleContext().setAccessibleName("userIcon");

        homeScreenTab.setViewportView(homeScreen);

        mainWindow.addTab("Home Screen", homeScreenTab);

        friendsListTab.setMaximumSize(new java.awt.Dimension(452, 200));
        friendsListTab.setPreferredSize(new java.awt.Dimension(452, 200));
        friendsListTab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                friendsListTabComponentShown(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 600));

        friendsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "username", "Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        friendsListTable.setMinimumSize(new java.awt.Dimension(452, 402));
        friendsListTable.setPreferredSize(new java.awt.Dimension(452, 402));
        friendsListTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(friendsListTable);
        if (friendsListTable.getColumnModel().getColumnCount() > 0) {
            friendsListTable.getColumnModel().getColumn(0).setResizable(false);
            friendsListTable.getColumnModel().getColumn(1).setResizable(false);
        }

        addFriendButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addFriendButton.setText("Add New Friend");
        addFriendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFriendButtonActionPerformed(evt);
            }
        });

        friendsRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "username", "Name", "Accepted"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        friendsRequestTable.setRowSelectionAllowed(false);
        friendsRequestTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        friendsRequestTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        friendsRequestTable.setShowGrid(true);
        friendsRequestTable.getTableHeader().setReorderingAllowed(false);
        friendsRequestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendsRequestTableMouseClicked(evt);
            }
        });
        friendsRequestTable.getModel().addTableModelListener(
            new TableModelListener() 
            {
                public void tableChanged(TableModelEvent evt) 
                {
                    System.out.println("Click Detected");
                    System.out.println(evt.getColumn());
                    System.out.println(evt.getFirstRow());
                    System.out.println(friendsRequestTable.getRowCount());
                    if(evt.getColumn() == 2){
                        int index = evt.getFirstRow();
                        Arrays b = null;
                        JSONObject friends_request = Application.this.fitapp.get_friends_request(b);
                        JSONObject argsr = friends_request.getJSONObject("args");
                        JSONArray usersr = argsr.getJSONArray("users");
                        JSONArray user_selected = usersr.getJSONArray(index);
                        String name_selected = user_selected.getString(1);
                        Application.this.fitapp.update_friends(name_selected);
                        DefaultTableModel tabler = (DefaultTableModel) friendsRequestTable.getModel();
                        tabler.removeRow(index);
                        friendsRequestTable = new JTable(tabler);
                    }
                }
            });
            jScrollPane2.setViewportView(friendsRequestTable);
            if (friendsRequestTable.getColumnModel().getColumnCount() > 0) {
                friendsRequestTable.getColumnModel().getColumn(0).setResizable(false);
                friendsRequestTable.getColumnModel().getColumn(1).setResizable(false);
                friendsRequestTable.getColumnModel().getColumn(2).setResizable(false);
            }

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(17, 17, 17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(22, 22, 22))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addFriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(495, 495, 495))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 413, Short.MAX_VALUE)
                    .addComponent(addFriendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(83, 83, 83))
            );

            friendsListTab.setViewportView(jPanel1);

            mainWindow.addTab("Friends List", friendsListTab);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainWindow)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainWindow, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void addExerciseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExerciseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addExerciseButtonActionPerformed

    private void usernameLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameLabelActionPerformed

    private void logInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInButtonActionPerformed
        if(usernameLabel.getText().length() == 0 || passwordLabel.getText().length() == 0){
            errorLabel.setText("username or password blank");
        }
        else{
            JSONObject result = this.fitapp.login(usernameLabel.getText(), passwordLabel.getText());
            int success = result.getInt("success");
            if (success == 1) {
                LogRegTab.remove(loginTab);
                LogRegTab.remove(registerTab);
                mainWindow.remove(LogRegTab);
                this.logedIn = true;
                mainWindow.addTab("Home Screen",homeScreenTab);
                mainWindow.addTab("Friends List",friendsListTab);
            }
            else{
                errorLabel.setText("incorrect username or password");
            }
        }
        
    }//GEN-LAST:event_logInButtonActionPerformed

    private void homeScreenTabFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_homeScreenTabFocusGained
        if (this.logedIn){    
            JSONObject home_screen = this.fitapp.get_home("",0,0,0,0,0,0,"");
            JSONObject args = home_screen.getJSONObject("args");
            String name = args.getString("name");
            Object isteps = args.get("steps");
            Object idaily_steps = args.get("daily_steps");
            String weight = String.valueOf(args.get("weight"));
            Object duration = args.get("duration");
            Object distance = args.get("distance");
            Object calories = args.get("calories");
            Object begin_date = args.get("begin_date");
            userName.setText(name);
            if(isteps == JSONObject.NULL){
                isteps = 0;
            }
            if(idaily_steps == JSONObject.NULL){
                idaily_steps = 0;
            }
            int steps = (Integer) isteps;
            int daily_steps = (Integer) idaily_steps;
            stepsNumber.setText(String.valueOf(steps));
            int percentage = 0;
            if (daily_steps != 0){
                percentage = (steps/daily_steps) * 100;
            }
            dailyStepsProgressBar.setValue(percentage);
            percentageText.setText(String.format("%s %% out of %s", percentage, daily_steps));
            weightNumber.setText(weight);
            
            if(duration != JSONObject.NULL){
                durationNumber.setText(String.format("%s minutes", duration));
                distanceNumber.setText(String.format("%s km", distance));
                caloriesNumber.setText(String.format("%s calories", calories));
                exerciseDateText.setText(String.format("%s", begin_date));
            }
            
        }
    }//GEN-LAST:event_homeScreenTabFocusGained

    private void homeScreenTabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_homeScreenTabComponentShown
        if (this.logedIn){    
            JSONObject home_screen = this.fitapp.get_home("",0,0,0,0,0,0,"");
            JSONObject args = home_screen.getJSONObject("args");
            String name = args.getString("name");
            Object isteps = args.get("steps");
            Object idaily_steps = args.get("daily_steps");
            String weight = String.valueOf(args.get("weight"));
            Object duration = args.get("duration");
            Object distance = args.get("distance");
            Object calories = args.get("calories");
            Object begin_date = args.get("begin_date");
            userName.setText(name);
            if(isteps == JSONObject.NULL){
                isteps = 0;
            }
            if(idaily_steps == JSONObject.NULL){
                idaily_steps = 0;
            }
            int steps = (Integer) isteps;
            int daily_steps = (Integer) idaily_steps;
            stepsNumber.setText(String.valueOf(steps));
            int percentage = 0;
            if (daily_steps != 0){
                percentage = (steps/daily_steps) * 100;
            }
            dailyStepsProgressBar.setValue(percentage);
            percentageText.setText(String.format("%s %% out of %s", percentage, daily_steps));
            weightNumber.setText(weight);
            
            if(duration != JSONObject.NULL){
                durationNumber.setText(String.format("%s minutes", duration));
                distanceNumber.setText(String.format("%s km", distance));
                caloriesNumber.setText(String.format("%s calories", calories));
                exerciseDateText.setText(String.format("%s", begin_date));
            }
            
        }
    }//GEN-LAST:event_homeScreenTabComponentShown

    private void setNewGoalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNewGoalsButtonActionPerformed
        NewGoalsPopUp.setVisible(true);
    }//GEN-LAST:event_setNewGoalsButtonActionPerformed

    private void setNewGoalsOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setNewGoalsOkButtonActionPerformed
        if(newStepsGoals.getText().length() > 0  && newCaloriesGoals.getText().length() > 0){
            int new_cals = Integer.valueOf(newCaloriesGoals.getText());
            int new_steps = Integer.valueOf(newStepsGoals.getText());
            this.fitapp.update_daily_goals(new_steps, new_cals);
            NewGoalsPopUp.setVisible(false);
        }
    }//GEN-LAST:event_setNewGoalsOkButtonActionPerformed

    private void friendsListTabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_friendsListTabComponentShown
        if(this.logedIn){
            // Friends List Table
            Arrays a = null;
            JSONObject friends_list = this.fitapp.get_friends_list(a);
            JSONObject args = friends_list.getJSONObject("args");
            JSONArray users = args.getJSONArray("users");
            DefaultTableModel table = (DefaultTableModel) friendsListTable.getModel();
            if (table.getRowCount() > 0){
                for (int i = table.getRowCount() - 1; i > -1; i--) {
                    table.removeRow(i);
                }
            }
            for (int i = 0 ; i < users.length(); i++){
               JSONArray user = users.getJSONArray(i);
               String[] data= {String.valueOf(user.get(0)), String.valueOf(user.get(1))};
               table.addRow(data);
            }
            friendsListTable = new JTable(table);
            
            // Friends Request Table
            Arrays b = null;
            JSONObject friends_request = this.fitapp.get_friends_request(b);
            JSONObject argsr = friends_request.getJSONObject("args");
            JSONArray usersr = argsr.getJSONArray("users");
            DefaultTableModel tabler = (DefaultTableModel) friendsRequestTable.getModel();
            if (tabler.getRowCount() > 0){
                for (int i = tabler.getRowCount() - 1; i > -1; i--) {
                    tabler.removeRow(i);
                }
            }
            for (int i = 0 ; i < usersr.length(); i++){
               JSONArray user = usersr.getJSONArray(i);
               Object[] data= {String.valueOf(user.get(0)), String.valueOf(user.get(1)), false};
               tabler.addRow(data);
            }
            friendsRequestTable = new JTable(tabler);
            
        }
    }//GEN-LAST:event_friendsListTabComponentShown

    private void addFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFriendButtonActionPerformed
        NewFriendPopUp.setVisible(true);
    }//GEN-LAST:event_addFriendButtonActionPerformed

    private void OkAddFriendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkAddFriendButtonActionPerformed
        if(NewFriendName.getText().length() > 0){
            JSONObject result = this.fitapp.create_friends(NewFriendName.getText());
            if (result.getInt("success") == 1){
                NewFriendPopUp.setVisible(false);
            }
            else{
                errorNewFriendAdd.setText("User not found or already added");
            }
        }
    }//GEN-LAST:event_OkAddFriendButtonActionPerformed

    private void friendsRequestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_friendsRequestTableMouseClicked
        
    }//GEN-LAST:event_friendsRequestTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FitnessApp fitapp = new FitnessApp();
        fitapp.get_AppId();
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Application app = new Application();
                app.setVisible(true);
                app.fitapp = fitapp;
                app.mainWindow.remove(app.homeScreenTab);
                app.mainWindow.remove(app.friendsListTab);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane LogRegTab;
    private javax.swing.JTextField NewFriendName;
    private javax.swing.JDialog NewFriendPopUp;
    private javax.swing.JDialog NewGoalsPopUp;
    private javax.swing.JButton OkAddFriendButton;
    private javax.swing.JButton addExerciseButton;
    private javax.swing.JButton addFriendButton;
    private javax.swing.JLabel caloriesNumber;
    private javax.swing.JProgressBar dailyStepsProgressBar;
    private javax.swing.JLabel distanceNumber;
    private javax.swing.JLabel durationNumber;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorNewFriendAdd;
    private javax.swing.JLabel exerciseDateText;
    private javax.swing.JButton friendsButton;
    private javax.swing.JScrollPane friendsListTab;
    private javax.swing.JTable friendsListTable;
    private javax.swing.JTable friendsRequestTable;
    private javax.swing.JPanel homeScreen;
    private javax.swing.JScrollPane homeScreenTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JInternalFrame lastExerciseFrame;
    private javax.swing.JLabel lastExerciseText;
    private javax.swing.JButton logInButton;
    private javax.swing.JPanel loginTab;
    private javax.swing.JTabbedPane mainWindow;
    private javax.swing.JTextField newCaloriesGoals;
    private javax.swing.JTextField newStepsGoals;
    private javax.swing.JTextField passwordLabel;
    private javax.swing.JLabel percentageText;
    private javax.swing.JPanel registerTab;
    private javax.swing.JButton setNewGoalsButton;
    private javax.swing.JButton setNewGoalsOkButton;
    private javax.swing.JInternalFrame stepsFrame;
    private javax.swing.JLabel stepsNumber;
    private javax.swing.JLabel stepsText;
    private javax.swing.JLabel userIcon;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField usernameLabel;
    private javax.swing.JInternalFrame weightFrame;
    private javax.swing.JLabel weightNumber;
    private javax.swing.JLabel weightText;
    // End of variables declaration//GEN-END:variables
}
