-- Create users

call create_user ('Minecreeper', 'mde', 'gc.pombo@campus.fct.unl.pt', 'Guilherme', 61, 169, '2000-04-19', 'male');
call create_user ('Loukios', 'mde', 'Loukios@campus.fct.unl.pt', 'Loukios', 69, 175, '2000-01-01', 'male');
call create_user ('Duff', 'mde', 'Duff@campus.fct.unl.pt', 'Duff', 69, 175, '2000-01-01', 'male');
call create_user ('Constantin', 'mde', 'Constantin@campus.fct.unl.pt', 'Constantin', 69, 175, '2000-01-01', 'male');
call create_user ('Cirino', 'mde', 'Cirino@campus.fct.unl.pt', 'Cirino', 69, 175, '2000-01-01', 'male');
call create_user ('Yonah', 'mde', 'Yonah@campus.fct.unl.pt', 'Yonah', 69, 175, '2000-01-01', 'male');
call create_user ('Paora', 'mde', 'Paora@campus.fct.unl.pt', 'Paora', 69, 175, '2000-01-01', 'male');
call create_user ('Arttu', 'mde', 'Arttu@campus.fct.unl.pt', 'Arttu', 69, 175, '2000-01-01', 'male');
call create_user ('Eriu', 'mde', 'Eriu@campus.fct.unl.pt', 'Eriu', 69, 175, '2000-01-01', 'female');
call create_user ('Marlis', 'mde', 'Marlis@campus.fct.unl.pt', 'Marlis', 69, 175, '2000-01-01', 'female');
call create_user ('Meabh', 'mde', 'Meabh@campus.fct.unl.pt', 'Meabh', 69, 175, '2000-01-01', 'female');
call create_user ('Amabilia', 'mde', 'Amabilia@campus.fct.unl.pt', 'Amabilia', 69, 175, '2000-01-01', 'female');
call create_user ('Valkyrie', 'mde', 'Valkyrie@campus.fct.unl.pt', 'Valkyrie', 69, 175, '2000-01-01', 'female');
call create_user ('Drishti', 'mde', 'Drishti@campus.fct.unl.pt', 'Drishti', 69, 175, '2000-01-01', 'female');
call create_user ('Leanne', 'mde', 'Leanne@campus.fct.unl.pt', 'Leanne', 69, 175, '2000-01-01', 'female');
call create_user ('Sunitha', 'mde', 'Sunitha@campus.fct.unl.pt', 'Sunitha', 69, 175, '2000-01-01', 'female');
call create_user ('Tirta', 'mde', 'Tirta@campus.fct.unl.pt', 'Tirta', 69, 175, '2000-01-01', 'female');
call create_user ('Augusta', 'mde', 'Augusta@campus.fct.unl.pt', 'Augusta', 69, 175, '2000-01-01', 'female');
call create_user ('Katelyn', 'mde', 'Katelyn@campus.fct.unl.pt', 'Katelyn', 69, 175, '2000-01-01', 'female');
call create_user ('Nona', 'mde', 'Nona@campus.fct.unl.pt', 'Nona', 69, 175, '2000-01-01', 'female');
call create_user ('Aarti', 'mde', 'Aarti@campus.fct.unl.pt', 'Aarti', 69, 175, '2000-01-01', 'female');
call create_user ('Dominika', 'mde', 'Dominika@campus.fct.unl.pt', 'Dominika', 69, 175, '2000-01-01', 'female');
call create_user ('Helene', 'mde', 'Helene@campus.fct.unl.pt', 'Helene', 69, 175, '2000-01-01', 'female');
call create_user ('Danica', 'mde', 'Danica@campus.fct.unl.pt', 'Danica', 69, 175, '2000-01-01', 'female');
call create_user ('Italia', 'mde', 'Italia@campus.fct.unl.pt', 'Italia', 69, 175, '2000-01-01', 'female');
call create_user ('Laura', 'mde', 'Laura@campus.fct.unl.pt', 'Laura', 69, 175, '2000-01-01', 'female');
call create_user ('Narses', 'mde', 'Narses@campus.fct.unl.pt', 'Narses', 69, 175, '2000-01-01', 'male');
call create_user ('Colwyn', 'mde', 'Colwyn@campus.fct.unl.pt', 'Colwyn', 69, 175, '2000-01-01', 'male');
call create_user ('Suhail', 'mde', 'Suhail@campus.fct.unl.pt', 'Suhail', 69, 175, '2000-01-01', 'male');
call create_user ('Ajith', 'mde', 'Ajith@campus.fct.unl.pt', 'Ajith', 69, 175, '2000-01-01', 'male');
call create_user ('Buhle', 'mde', 'Buhle@campus.fct.unl.pt', 'Buhle', 69, 175, '2000-01-01', 'male');
call create_user ('Davit', 'mde', 'Davit@campus.fct.unl.pt', 'Davit', 69, 175, '2000-01-01', 'male');
call create_user ('Sander', 'mde', 'Sander@campus.fct.unl.pt', 'Sander', 69, 175, '2000-01-01', 'male');
call create_user ('Kumaran', 'mde', 'Kumaran@campus.fct.unl.pt', 'Kumaran', 69, 175, '2000-01-01', 'male');
call create_user ('Narayana', 'mde', 'Narayana@campus.fct.unl.pt', 'Narayana', 69, 175, '2000-01-01', 'male');

-- Create activities

call create_activities_template ('Squats', NULL, NULL, 8);
call create_activities_template ('Jumping Jacks', NULL, NULL, 16);
call create_activities_template ('Crab Walk', NULL, NULL, 10);
call create_activities_template ('Jogging', NULL, 60, NULL);
call create_activities_template ('Crunches', NULL, NULL, 6);
call create_activities_template ('Wall Pushups', NULL, NULL, 7);
call create_activities_template ('Lunges', NULL, NULL, 6);
call create_activities_template ('High Knees', NULL, NULL, 6);
call create_activities_template ('Wall Sit', NULL, NULL, TO_NUMBER('3.6', '9.99'));

-- Create friends

call create_friends ( 2, 7);
call create_friends ( 5, 4);
call create_friends ( 2, 26);
call create_friends ( 7, 3);
call create_friends ( 2, 5);
call create_friends ( 6, 16);
call create_friends ( 18, 21);
call create_friends ( 16, 1);
call create_friends ( 2, 1);
call create_friends ( 28, 1);
call create_friends ( 2, 12);
call create_friends ( 4, 3);
call create_friends ( 25, 6);
call create_friends ( 2, 8);
call create_friends ( 14, 19);
call create_friends ( 4, 17);
call create_friends ( 6, 23);
call create_friends ( 24, 12);
call create_friends ( 16, 11);

-- Create accept all invitations

call update_friends ( 7, 2);
call update_friends ( 4, 5);
call update_friends ( 26, 2);
call update_friends ( 3, 7);
call update_friends ( 5, 2);
call update_friends ( 16, 6);
call update_friends ( 21, 18);
call update_friends ( 1, 16);
call update_friends ( 1, 2);
call update_friends ( 1, 28);
call update_friends ( 12, 2);
call update_friends ( 3, 4);
call update_friends ( 6, 25);
call update_friends ( 8, 2);
call update_friends ( 19, 14);
call update_friends ( 17, 4);
call update_friends ( 23, 6);
call update_friends ( 12, 24);
call update_friends ( 11, 16);

-- Start exercises

call create_exercises(4,1);
call create_exercises(4,28);
call create_exercises(3,4);
call create_exercises(4,12);
call create_exercises(9,5);
call create_exercises(4,13);
call create_exercises(5,7);
call create_exercises(4,14);
call create_exercises(4,8);
call create_exercises(4,15);
call create_exercises(7,9);
call create_exercises(6,17);
call create_exercises(5,10);
call create_exercises(4,18);
call create_exercises(4,11);

-- Finish exercises

call update_exercises(1,23,0,159);
call update_exercises(28,10,0,153);
call update_exercises(4,0,0,132);
call update_exercises(12,20,0,179);
call update_exercises(5,0,0,139);
call update_exercises(13,30,0,146);
call update_exercises(7,0,0,179);
call update_exercises(14,40,0,145);
call update_exercises(8,20,0,146);
call update_exercises(15,30,0,179);
call update_exercises(9,0,0,211);
call update_exercises(17,0,0,146);
call update_exercises(10,0,0,132);
call update_exercises(18,10,0,146);
call update_exercises(11,15,0,153);

-- Online/offline and transactions

update fit_user set active = 1 where id = 1;
call create_transactions (1, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 1;
update fit_user set active = 0 where id = 1;
update fit_user set active = 1 where id = 2;
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 2;
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 2;
update fit_user set active = 1 where id = 3;
call create_transactions (3, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 3;
call create_transactions (3, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 3;
update fit_user set active = 1 where id = 4;
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 4;
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 4;
update fit_user set active = 1 where id = 5;
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 5;
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 5;
update fit_user set active = 1 where id = 6;
call create_transactions (6, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 6;
call create_transactions (6, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 6;
update fit_user set active = 1 where id = 7;
call create_transactions (7, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 7;
update fit_user set active = 0 where id = 7;
update fit_user set active = 1 where id = 8;
call create_transactions (8, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 8;
call create_transactions (8, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 8;
update fit_user set active = 1 where id = 9;
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 9;
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 9;
update fit_user set active = 1 where id = 10;
call create_transactions (10, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 10;
call create_transactions (10, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 10;
update fit_user set active = 1 where id = 11;
call create_transactions (11, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 11;
update fit_user set active = 0 where id = 11;
update fit_user set active = 1 where id = 12;
call create_transactions (12, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 12;
call create_transactions (12, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 12;
update fit_user set active = 1 where id = 13;
call create_transactions (13, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 13;
call create_transactions (13, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 13;
update fit_user set active = 1 where id = 14;
call create_transactions (14, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 14;
update fit_user set active = 0 where id = 14;
update fit_user set active = 1 where id = 15;
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 15;
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 15;
update fit_user set active = 1 where id = 16;
call create_transactions (16, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 16;
update fit_user set active = 0 where id = 16;
update fit_user set active = 1 where id = 17;
call create_transactions (17, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 17;
call create_transactions (17, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 17;
update fit_user set active = 1 where id = 18;
call create_transactions (18, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 18;
update fit_user set active = 0 where id = 18;
update fit_user set active = 1 where id = 19;
call create_transactions (19, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 19;
update fit_user set active = 0 where id = 19;
update fit_user set active = 1 where id = 20;
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 20;
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 20;
update fit_user set active = 1 where id = 21;
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 21;
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 21;
update fit_user set active = 1 where id = 22;
call create_transactions (22, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 22;
call create_transactions (22, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 22;
update fit_user set active = 1 where id = 23;
call create_transactions (23, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 23;
update fit_user set active = 0 where id = 23;
update fit_user set active = 1 where id = 24;
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 24;
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 24;
update fit_user set active = 1 where id = 25;
call create_transactions (25, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 25;
call create_transactions (25, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 25;
update fit_user set active = 1 where id = 26;
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 26;
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 26;
update fit_user set active = 1 where id = 27;
call create_transactions (27, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 27;
call create_transactions (27, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 27;
update fit_user set active = 1 where id = 28;
call create_transactions (28, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 28;
call create_transactions (28, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 28;
update fit_user set active = 1 where id = 29;
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 29;
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 29;
update fit_user set active = 1 where id = 30;
call create_transactions (30, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 30;
update fit_user set active = 0 where id = 30;
update fit_user set active = 1 where id = 31;
call create_transactions (31, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 31;
call create_transactions (31, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 31;
update fit_user set active = 1 where id = 32;
call create_transactions (32, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 32;
update fit_user set active = 0 where id = 32;
update fit_user set active = 1 where id = 33;
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 33;
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 33;
update fit_user set active = 1 where id = 34;
call create_transactions (34, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 34;
call create_transactions (34, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 34;
update fit_user set active = 1 where id = 35;
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 35;
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 35;

-- update leaderboard

call update_leaderboard (1,1);
call update_leaderboard (2,1);
call update_leaderboard (3,1);
call update_leaderboard (4,1);
call update_leaderboard (5,1);
call update_leaderboard (6,1);
call update_leaderboard (7,1);
call update_leaderboard (8,1);
call update_leaderboard (9,1);
call update_leaderboard (10,1);
call update_leaderboard (11,1);
call update_leaderboard (12,1);
call update_leaderboard (13,1);
call update_leaderboard (14,1);
call update_leaderboard (15,1);
call update_leaderboard (16,1);
call update_leaderboard (17,1);
call update_leaderboard (18,1);
call update_leaderboard (19,1);
call update_leaderboard (20,1);
call update_leaderboard (21,1);
call update_leaderboard (22,1);
call update_leaderboard (23,1);
call update_leaderboard (24,1);
call update_leaderboard (25,1);
call update_leaderboard (26,1);
call update_leaderboard (27,1);
call update_leaderboard (28,1);
call update_leaderboard (29,1);
call update_leaderboard (30,1);
call update_leaderboard (31,1);
call update_leaderboard (32,1);
call update_leaderboard (33,1);
call update_leaderboard (34,1);
call update_leaderboard (35,1);
call update_leaderboard (1,2);
call update_leaderboard (2,2);
call update_leaderboard (3,2);
call update_leaderboard (4,2);
call update_leaderboard (5,2);
call update_leaderboard (6,2);
call update_leaderboard (7,2);
call update_leaderboard (8,2);
call update_leaderboard (9,2);
call update_leaderboard (10,2);
call update_leaderboard (11,2);
call update_leaderboard (12,2);
call update_leaderboard (13,2);
call update_leaderboard (14,2);
call update_leaderboard (15,2);
call update_leaderboard (16,2);
call update_leaderboard (17,2);
call update_leaderboard (18,2);
call update_leaderboard (19,2);
call update_leaderboard (20,2);
call update_leaderboard (21,2);
call update_leaderboard (22,2);
call update_leaderboard (23,2);
call update_leaderboard (24,2);
call update_leaderboard (25,2);
call update_leaderboard (26,2);
call update_leaderboard (27,2);
call update_leaderboard (28,2);
call update_leaderboard (29,2);
call update_leaderboard (30,2);
call update_leaderboard (31,2);
call update_leaderboard (32,2);
call update_leaderboard (33,2);
call update_leaderboard (34,2);
call update_leaderboard (35,2);
call update_leaderboard (1,3);
call update_leaderboard (2,3);
call update_leaderboard (3,3);
call update_leaderboard (4,3);
call update_leaderboard (5,3);
call update_leaderboard (6,3);
call update_leaderboard (7,3);
call update_leaderboard (8,3);
call update_leaderboard (9,3);
call update_leaderboard (10,3);
call update_leaderboard (11,3);
call update_leaderboard (12,3);
call update_leaderboard (13,3);
call update_leaderboard (14,3);
call update_leaderboard (15,3);
call update_leaderboard (16,3);
call update_leaderboard (17,3);
call update_leaderboard (18,3);
call update_leaderboard (19,3);
call update_leaderboard (20,3);
call update_leaderboard (21,3);
call update_leaderboard (22,3);
call update_leaderboard (23,3);
call update_leaderboard (24,3);
call update_leaderboard (25,3);
call update_leaderboard (26,3);
call update_leaderboard (27,3);
call update_leaderboard (28,3);
call update_leaderboard (29,3);
call update_leaderboard (30,3);
call update_leaderboard (31,3);
call update_leaderboard (32,3);
call update_leaderboard (33,3);
call update_leaderboard (34,3);
call update_leaderboard (35,3);
call update_leaderboard (1,4);
call update_leaderboard (2,4);
call update_leaderboard (3,4);
call update_leaderboard (4,4);
call update_leaderboard (5,4);
call update_leaderboard (6,4);
call update_leaderboard (7,4);
call update_leaderboard (8,4);
call update_leaderboard (9,4);
call update_leaderboard (10,4);
call update_leaderboard (11,4);
call update_leaderboard (12,4);
call update_leaderboard (13,4);
call update_leaderboard (14,4);
call update_leaderboard (15,4);
call update_leaderboard (16,4);
call update_leaderboard (17,4);
call update_leaderboard (18,4);
call update_leaderboard (19,4);
call update_leaderboard (20,4);
call update_leaderboard (21,4);
call update_leaderboard (22,4);
call update_leaderboard (23,4);
call update_leaderboard (24,4);
call update_leaderboard (25,4);
call update_leaderboard (26,4);
call update_leaderboard (27,4);
call update_leaderboard (28,4);
call update_leaderboard (29,4);
call update_leaderboard (30,4);
call update_leaderboard (31,4);
call update_leaderboard (32,4);
call update_leaderboard (33,4);
call update_leaderboard (34,4);
call update_leaderboard (35,4);
call update_leaderboard (1,5);
call update_leaderboard (2,5);
call update_leaderboard (3,5);
call update_leaderboard (4,5);
call update_leaderboard (5,5);
call update_leaderboard (6,5);
call update_leaderboard (7,5);
call update_leaderboard (8,5);
call update_leaderboard (9,5);
call update_leaderboard (10,5);
call update_leaderboard (11,5);
call update_leaderboard (12,5);
call update_leaderboard (13,5);
call update_leaderboard (14,5);
call update_leaderboard (15,5);
call update_leaderboard (16,5);
call update_leaderboard (17,5);
call update_leaderboard (18,5);
call update_leaderboard (19,5);
call update_leaderboard (20,5);
call update_leaderboard (21,5);
call update_leaderboard (22,5);
call update_leaderboard (23,5);
call update_leaderboard (24,5);
call update_leaderboard (25,5);
call update_leaderboard (26,5);
call update_leaderboard (27,5);
call update_leaderboard (28,5);
call update_leaderboard (29,5);
call update_leaderboard (30,5);
call update_leaderboard (31,5);
call update_leaderboard (32,5);
call update_leaderboard (33,5);
call update_leaderboard (34,5);
call update_leaderboard (35,5);
call update_leaderboard (1,6);
call update_leaderboard (2,6);
call update_leaderboard (3,6);
call update_leaderboard (4,6);
call update_leaderboard (5,6);
call update_leaderboard (6,6);
call update_leaderboard (7,6);
call update_leaderboard (8,6);
call update_leaderboard (9,6);
call update_leaderboard (10,6);
call update_leaderboard (11,6);
call update_leaderboard (12,6);
call update_leaderboard (13,6);
call update_leaderboard (14,6);
call update_leaderboard (15,6);
call update_leaderboard (16,6);
call update_leaderboard (17,6);
call update_leaderboard (18,6);
call update_leaderboard (19,6);
call update_leaderboard (20,6);
call update_leaderboard (21,6);
call update_leaderboard (22,6);
call update_leaderboard (23,6);
call update_leaderboard (24,6);
call update_leaderboard (25,6);
call update_leaderboard (26,6);
call update_leaderboard (27,6);
call update_leaderboard (28,6);
call update_leaderboard (29,6);
call update_leaderboard (30,6);
call update_leaderboard (31,6);
call update_leaderboard (32,6);
call update_leaderboard (33,6);
call update_leaderboard (34,6);
call update_leaderboard (35,6);
call update_leaderboard (1,7);
call update_leaderboard (2,7);
call update_leaderboard (3,7);
call update_leaderboard (4,7);
call update_leaderboard (5,7);
call update_leaderboard (6,7);
call update_leaderboard (7,7);
call update_leaderboard (8,7);
call update_leaderboard (9,7);
call update_leaderboard (10,7);
call update_leaderboard (11,7);
call update_leaderboard (12,7);
call update_leaderboard (13,7);
call update_leaderboard (14,7);
call update_leaderboard (15,7);
call update_leaderboard (16,7);
call update_leaderboard (17,7);
call update_leaderboard (18,7);
call update_leaderboard (19,7);
call update_leaderboard (20,7);
call update_leaderboard (21,7);
call update_leaderboard (22,7);
call update_leaderboard (23,7);
call update_leaderboard (24,7);
call update_leaderboard (25,7);
call update_leaderboard (26,7);
call update_leaderboard (27,7);
call update_leaderboard (28,7);
call update_leaderboard (29,7);
call update_leaderboard (30,7);
call update_leaderboard (31,7);
call update_leaderboard (32,7);
call update_leaderboard (33,7);
call update_leaderboard (34,7);
call update_leaderboard (35,7);
call update_leaderboard (1,8);
call update_leaderboard (2,8);
call update_leaderboard (3,8);
call update_leaderboard (4,8);
call update_leaderboard (5,8);
call update_leaderboard (6,8);
call update_leaderboard (7,8);
call update_leaderboard (8,8);
call update_leaderboard (9,8);
call update_leaderboard (10,8);
call update_leaderboard (11,8);
call update_leaderboard (12,8);
call update_leaderboard (13,8);
call update_leaderboard (14,8);
call update_leaderboard (15,8);
call update_leaderboard (16,8);
call update_leaderboard (17,8);
call update_leaderboard (18,8);
call update_leaderboard (19,8);
call update_leaderboard (20,8);
call update_leaderboard (21,8);
call update_leaderboard (22,8);
call update_leaderboard (23,8);
call update_leaderboard (24,8);
call update_leaderboard (25,8);
call update_leaderboard (26,8);
call update_leaderboard (27,8);
call update_leaderboard (28,8);
call update_leaderboard (29,8);
call update_leaderboard (30,8);
call update_leaderboard (31,8);
call update_leaderboard (32,8);
call update_leaderboard (33,8);
call update_leaderboard (34,8);
call update_leaderboard (35,8);
call update_leaderboard (1,9);
call update_leaderboard (2,9);
call update_leaderboard (3,9);
call update_leaderboard (4,9);
call update_leaderboard (5,9);
call update_leaderboard (6,9);
call update_leaderboard (7,9);
call update_leaderboard (8,9);
call update_leaderboard (9,9);
call update_leaderboard (10,9);
call update_leaderboard (11,9);
call update_leaderboard (12,9);
call update_leaderboard (13,9);
call update_leaderboard (14,9);
call update_leaderboard (15,9);
call update_leaderboard (16,9);
call update_leaderboard (17,9);
call update_leaderboard (18,9);
call update_leaderboard (19,9);
call update_leaderboard (20,9);
call update_leaderboard (21,9);
call update_leaderboard (22,9);
call update_leaderboard (23,9);
call update_leaderboard (24,9);
call update_leaderboard (25,9);
call update_leaderboard (26,9);
call update_leaderboard (27,9);
call update_leaderboard (28,9);
call update_leaderboard (29,9);
call update_leaderboard (30,9);
call update_leaderboard (31,9);
call update_leaderboard (32,9);
call update_leaderboard (33,9);
call update_leaderboard (34,9);
call update_leaderboard (35,9);
