-- Generated by Oracle SQL Developer Data Modeler 20.4.1.406.0906
--   at:        2021-04-30 20:30:12 BST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE activities_template (
    id             INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    name           VARCHAR2(64) NOT NULL,
    cal_step_mult  NUMBER(5, 2),
    cal_dist_mutl  NUMBER(5, 2),
    cal_time_mult  NUMBER(5, 2)
)
LOGGING;

ALTER TABLE activities_template ADD CONSTRAINT activities_template_pk PRIMARY KEY ( id );

ALTER TABLE activities_template ADD CONSTRAINT activities_template__un UNIQUE ( name );

CREATE TABLE daily_goals (
    fit_user_id  INTEGER NOT NULL,
    daily_steps  NUMBER(7, 2) DEFAULT 0,
    daily_cals   NUMBER(7, 2) DEFAULT 0
)
LOGGING;

ALTER TABLE daily_goals ADD CONSTRAINT daily_goals_pk PRIMARY KEY ( fit_user_id );

CREATE TABLE daily_status (
    daily_id     INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    distance     NUMBER(7, 2) NOT NULL,
    steps        NUMBER(7, 2) NOT NULL,
    weight       NUMBER(5, 2) NOT NULL,
    calories     NUMBER(7, 2) NOT NULL,
    completed    NUMBER(1) DEFAULT 0 NOT NULL,
    status_date  DATE NOT NULL
)
LOGGING;

ALTER TABLE daily_status ADD CONSTRAINT daily_status_pk PRIMARY KEY ( daily_id );

CREATE TABLE exercises (
    ex_id                   INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    activities_template_id  INTEGER NOT NULL,
    fit_user_id             INTEGER NOT NULL,
    duration                INTERVAL DAY(9) TO SECOND(0),
    steps                   NUMBER(7, 2),
    distance                NUMBER(7, 2),
    calories                NUMBER(7, 2),
    begin_date              TIMESTAMP WITH LOCAL TIME ZONE,
    end_date                TIMESTAMP WITH LOCAL TIME ZONE,
    avg_bpm                 NUMBER(3)
)
LOGGING;

ALTER TABLE exercises ADD CONSTRAINT exercises_pk PRIMARY KEY ( ex_id );

CREATE TABLE fit_user (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    username     VARCHAR2(64) NOT NULL,
    password     VARCHAR2(64) NOT NULL,
    email        VARCHAR2(128) NOT NULL,
    active       NUMBER,
    pt           NUMBER,
    fit_user_id  INTEGER
)
LOGGING;

ALTER TABLE fit_user ADD CONSTRAINT user_pk PRIMARY KEY ( id );

ALTER TABLE fit_user ADD CONSTRAINT fit_user__un UNIQUE ( username );

CREATE TABLE friends_leaderboard (
    id                             INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    totals_fit_user_id             INTEGER NOT NULL,
    totals_activities_template_id  INTEGER NOT NULL,
    place                          NUMBER(7)
)
LOGGING;

CREATE UNIQUE INDEX friends_leaderboard__idx ON
    friends_leaderboard (
        totals_fit_user_id
    ASC,
        totals_activities_template_id
    ASC )
        LOGGING;

ALTER TABLE friends_leaderboard ADD CONSTRAINT friends_leaderboard_pk PRIMARY KEY ( id );

CREATE TABLE friends_list (
    fit_user_id   INTEGER NOT NULL,
    fit_user_id1  INTEGER NOT NULL,
    accepted      NUMBER(1)
)
LOGGING;


ALTER TABLE friends_list ADD CONSTRAINT friends_list_pkv1 PRIMARY KEY ( fit_user_id1,
                                                                        fit_user_id );


CREATE TABLE notice (
    n_id             INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    exercises_ex_id  INTEGER NOT NULL,
    fit_user_id      INTEGER NOT NULL,
    date_hour        TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    title            VARCHAR2(64) NOT NULL,
    description      VARCHAR2(128) NOT NULL,
    brief            VARCHAR2(64) NOT NULL
)
LOGGING;

ALTER TABLE notice ADD CONSTRAINT notice_pk PRIMARY KEY ( n_id );

CREATE TABLE profile (
    fit_user_id  INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    name         VARCHAR2(128) NOT NULL,
    weight       NUMBER(5, 2),
    height       NUMBER(5, 2),
    bday         DATE NOT NULL,
    gender       VARCHAR2(64),
    premium      NUMBER
)
LOGGING;

ALTER TABLE profile ADD CONSTRAINT profile_pk PRIMARY KEY ( fit_user_id );

CREATE TABLE totals (
    fit_user_id             INTEGER NOT NULL,
    activities_template_id  INTEGER NOT NULL,
    distance                NUMBER(7, 2),
    calories                NUMBER(7, 2)
)
LOGGING;

ALTER TABLE totals ADD CONSTRAINT totals_pk PRIMARY KEY ( fit_user_id,
                                                          activities_template_id );

CREATE TABLE transaction (
    tr_id        INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    value        NUMBER(4, 2) NOT NULL,
    t_date       DATE NOT NULL
)
LOGGING;

ALTER TABLE transaction ADD CONSTRAINT transaction_pk PRIMARY KEY ( tr_id );

CREATE TABLE user_activity (
    id           INTEGER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    fit_user_id  INTEGER NOT NULL,
    act_date     DATE,
    begin_date   TIMESTAMP WITH LOCAL TIME ZONE,
    end_date     TIMESTAMP WITH LOCAL TIME ZONE,
    paid         NUMBER(1)
)
LOGGING;

ALTER TABLE user_activity ADD CONSTRAINT user_activity_pk PRIMARY KEY ( id );

ALTER TABLE daily_goals
    ADD CONSTRAINT daily_goals_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE daily_status
    ADD CONSTRAINT daily_status_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE exercises
    ADD CONSTRAINT exercises_act_fk FOREIGN KEY ( activities_template_id )
        REFERENCES activities_template ( id )
    NOT DEFERRABLE;

ALTER TABLE exercises
    ADD CONSTRAINT exercises_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE fit_user
    ADD CONSTRAINT fit_user_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
    NOT DEFERRABLE;

ALTER TABLE friends_leaderboard
    ADD CONSTRAINT friends_leaderboard_totals_fk FOREIGN KEY ( totals_fit_user_id,
                                                               totals_activities_template_id )
        REFERENCES totals ( fit_user_id,
                            activities_template_id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE friends_list
    ADD CONSTRAINT friends_list_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE friends_list
    ADD CONSTRAINT friends_list_fit_user_fkv2 FOREIGN KEY ( fit_user_id1 )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE notice
    ADD CONSTRAINT notice_exercises_fk FOREIGN KEY ( exercises_ex_id )
        REFERENCES exercises ( ex_id )
    NOT DEFERRABLE;

ALTER TABLE notice
    ADD CONSTRAINT notice_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE profile
    ADD CONSTRAINT profile_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE totals
    ADD CONSTRAINT totals_activities_template_fk FOREIGN KEY ( activities_template_id )
        REFERENCES activities_template ( id )
    NOT DEFERRABLE;

ALTER TABLE totals
    ADD CONSTRAINT totals_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE transaction
    ADD CONSTRAINT transaction_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE user_activity
    ADD CONSTRAINT user_activity_fit_user_fk FOREIGN KEY ( fit_user_id )
        REFERENCES fit_user ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

create or replace NONEDITIONABLE procedure create_activities_template(
    iname           VARCHAR2,
    ical_step_mult  NUMBER,
    ical_dist_mutl  NUMBER,
    ical_time_mult  NUMBER
) is
    aux_act_id INTEGER;
begin
    insert into activities_template (name,cal_step_mult,cal_dist_mutl,cal_time_mult)
    values (iname,ical_step_mult,ical_dist_mutl,ical_time_mult);

    SELECT id 
    INTO aux_act_id
    FROM activities_template 
    WHERE name = iname;

    FOR aRow IN (
        SELECT id
        FROM fit_user
    )
    LOOP

    insert into totals (
        fit_user_id,
        activities_template_id,
        distance,
        calories
    )
    values (
        aRow.id,
        aux_act_id,
        0,
        0
    );

    insert into friends_leaderboard (
        totals_fit_user_id,
        totals_activities_template_id,
        place
    )
    values (
        aRow.id,
        aux_act_id,
        1
    );

    END LOOP;
end;

create or replace procedure create_daily_goals(
    ifit_user_id  INTEGER,
    idaily_steps  NUMBER,
    idaily_cals   NUMBER
) as
begin
    insert into daily_goals (fit_user_id,daily_steps,daily_cals)
    values (ifit_user_id,idaily_steps,idaily_cals);
end;

create or replace procedure create_daily_status(
    ifit_user_id  INTEGER
) as
begin
    insert into daily_status (
        status_date,
        fit_user_id,
        distance,
        steps,
        weight,
        calories,
        completed
    )
    values (
        (select sysdate from dual),
        ifit_user_id,
        0,
        0,
        0,
        0,
        0
    );
end;

create or replace procedure create_exercises(
    iactivities_template_id  INTEGER,
    ifit_user_id             INTEGER
) as
begin
    insert into exercises (activities_template_id,fit_user_id,begin_date)
    values (iactivities_template_id,ifit_user_id,(SELECT SYSTIMESTAMP FROM dual));
end;

create or replace procedure create_friends(
    ifit_user_id     INTEGER,
    ifit_user_id1    INTEGER
) as
begin
    insert into friends_list (fit_user_id,fit_user_id1)
    values (ifit_user_id,ifit_user_id1);
end;

create or replace procedure create_notice(
    iexercises_ex_id  INTEGER,
    ifit_user_id      INTEGER,
    ititle            VARCHAR2,
    idescription      VARCHAR2,
    ibrief            VARCHAR2
) as
begin
    insert into notice (exercises_ex_id,fit_user_id,date_hour,title,description,brief)
    values (iexercises_ex_id,ifit_user_id,(SELECT SYSTIMESTAMP FROM dual),ititle,idescription,ibrief);
end;

create or replace procedure create_transactions(
    ifit_user_id  INTEGER,
    ivalue        NUMBER
) as
begin
    insert into transaction (
        fit_user_id,
        value,
        t_date       
    )
    values (
        ifit_user_id,
        ivalue,
        (SELECT SYSTIMESTAMP FROM dual)
    );
end;

create or replace procedure create_user(
    iusername     VARCHAR2,
    ipassword     VARCHAR2,
    iemail        VARCHAR2,
    iname         VARCHAR2,
    iweight       NUMBER,
    iheight       NUMBER,
    ibday         DATE,
    igender       VARCHAR2
) is
    aux_fit_user_id INTEGER;
begin

    insert into fit_user (username, password, email, active, pt)
    values (iusername,ipassword,iemail, 0, 0);
    
    
    SELECT id 
    INTO aux_fit_user_id
    FROM fit_user 
    WHERE username = iusername;
    
    
    insert into profile (fit_user_id, name, weight, height, bday, gender, premium)
    values (aux_fit_user_id, iname, iweight, iheight, ibday, igender, 0);
    
    insert into daily_goals (fit_user_id,daily_steps,daily_cals)
    values (aux_fit_user_id,0,0);
    
    FOR aRow IN (
        SELECT id
        FROM activities_template
    )
    LOOP
    
    
    insert into totals (
        fit_user_id,
        activities_template_id,
        distance,
        calories
    )
    values (
        aux_fit_user_id,
        aRow.id,
        0,
        0
    );
    
    
    insert into friends_leaderboard (
        totals_fit_user_id,
        totals_activities_template_id,
        place
    )
    values (
        aux_fit_user_id,
        aRow.id,
        1
    );
    
    END LOOP;
end;

create or replace procedure create_user_activity(
    ifit_user_id  INTEGER
) as
begin
    insert into user_activity (
        fit_user_id,
        act_date,
        begin_date,
        paid
    )
    values (
        ifit_user_id,
        TO_DATE(sysdate,'YYYY-MM-DD'),
        (SELECT SYSTIMESTAMP FROM dual),
        (SELECT premium from profile where fit_user_id = ifit_user_id)
    );
end;

create or replace NONEDITIONABLE procedure delect_user (
    p_ID in FIT_USER.ID%type
) is
begin
    delete from FIT_USER
    where ID = p_ID;
end;

create or replace NONEDITIONABLE procedure delete_activities (
    p_ID in ACTIVITIES_TEMPLATE.ID%type
) is
    begin
    delete from ACTIVITIES_TEMPLATE
    where ID = p_ID;
end;

create or replace NONEDITIONABLE procedure delete_friend (
    ifit_user_id1 in FRIENDS_LIST.FIT_USER_ID1%type,
    ifit_user_id in FRIENDS_LIST.FIT_USER_ID%type
) is
begin
    delete from FRIENDS_LIST
    where fit_user_id1 = ifit_user_id1 and fit_user_id = ifit_user_id;
end;

create or replace NONEDITIONABLE procedure update_exercises (
    ifit_user_id in fit_user.id%type,
    idistance in EXERCISES.DISTANCE%type,
    isteps in EXERCISES.STEPS%type,
    ibpm in EXERCISES.avg_bpm%type
) is
    ex_calories       EXERCISES.CALORIES%type;
    ex_end_date       EXERCISES.end_date%type;
    ex_duration       EXERCISES.duration%type;
    ex_duration_min   number(38);
    ex_begin_date     EXERCISES.begin_date%type;
    act_id            EXERCISES.activities_template_id%type;
    iex_id            EXERCISES.ex_id%type;
    ex_cal_step_mult  activities_template.cal_step_mult%type;
    ex_cal_dist_mutl  activities_template.cal_dist_mutl%type;
    ex_cal_time_mult  activities_template.cal_time_mult%type;
begin
    select SYSTIMESTAMP 
    into ex_end_date
    from dual;

    select ex_id
    into iex_id
    from exercises
    where fit_user_id = ifit_user_id
    and end_date is null;

    select 
        activities_template_id,
        begin_date
    into 
        act_id,
        ex_begin_date
    from exercises
    where ex_id = iex_id;

    select 
        cal_step_mult,
        cal_dist_mutl,
        cal_time_mult
    into
        ex_cal_step_mult,
        ex_cal_dist_mutl,
        ex_cal_time_mult
    from activities_template
    where id = act_id;

    ex_duration := ex_end_date - ex_begin_date;

    ex_duration_min := abs( extract( minute from ex_duration ) 
        + extract( hour from ex_duration ) * 60 
        + extract( day from ex_duration ) * 60 * 24
        );

    ex_calories := 0;

    if ex_cal_step_mult is not null
    then
        ex_calories := ex_calories + isteps*ex_cal_step_mult;
    end if;

    if ex_cal_dist_mutl is not null
    then
        ex_calories := ex_calories + idistance*ex_cal_dist_mutl;
    end if;

    if ex_cal_time_mult is not null
    then
        ex_calories := ex_calories + ex_duration_min*ex_cal_time_mult;
    end if;

    update EXERCISES set
        distance = idistance,
        calories = ex_calories,
        end_date = ex_end_date,
        duration = ex_duration,
        steps = isteps,
        avg_bpm = ibpm
    where ex_id = iex_id;
end;

create or replace NONEDITIONABLE procedure update_friends (
    ifit_user_id in FRIENDS_LIST.FIT_USER_ID%type,
    ifit_user_id1 in FRIENDS_LIST.FIT_USER_ID1%type
) is
begin
    update FRIENDS_LIST set
    accepted = 1
    where fit_user_id1 = ifit_user_id and fit_user_id = ifit_user_id1;

    insert into friends_list (fit_user_id,fit_user_id1,accepted)
    values (ifit_user_id,ifit_user_id1,1);
end;

create or replace NONEDITIONABLE procedure update_leaderboard (
    itotals_fit_user_id in FRIENDS_LEADERBOARD.TOTALS_FIT_USER_ID%type,
    itotals_activities_template_id in FRIENDS_LEADERBOARD.TOTALS_ACTIVITIES_TEMPLATE_ID%type
) is
    aux_fit_user_calories TOTALS.CALORIES%type;
    aux_fit_friend_calories TOTALS.CALORIES%type;
    place_var FRIENDS_LEADERBOARD.place%type;
begin

    select calories
    into aux_fit_user_calories
    from totals 
    where fit_user_id = itotals_fit_user_id and activities_template_id = itotals_activities_template_id;

    place_var := 1;

    for aRow in (
    select fit_user_id1
    from friends_list
    where accepted = 1
    )
    LOOP
        select calories 
        into aux_fit_friend_calories
        from totals 
        where activities_template_id = itotals_activities_template_id 
        and fit_user_id = aRow.fit_user_id1;

        if 
            aux_fit_user_calories < aux_fit_friend_calories
        then
            place_var := place_var + 1;
        end if;
    END LOOP;

    update FRIENDS_LEADERBOARD set
    place = place_var
    where totals_fit_user_id = itotals_fit_user_id and totals_activities_template_id = itotals_activities_template_id;
end;

create or replace NONEDITIONABLE function check_password
  (user_name VARCHAR2, passin VARCHAR2)
  return INTEGER
  is
  table_pass VARCHAR2(64);
  user_id INTEGER;
  begin
    select id, password
      into user_id, table_pass
      from fit_user
    where fit_user.username = user_name;

    if table_pass = passin then
      return user_id;
    else
      return 0;
    end if;
  end;
  
create or replace NONEDITIONABLE function total_paid(
    ifit_user_id fit_user.id%type,
    begin_date  date, 
    end_date    date
)
return transaction.value%type
is
    total_val transaction.value%type;
begin
    select sum(value)
    into total_val
    from (
        select value
        from transaction
        where t_date 
        between begin_date and end_date
        and fit_user_id = ifit_user_id
    );

    if total_val is null
    then
        return 0;
    end if;

    return total_val;
end;

create or replace NONEDITIONABLE trigger notice_trg
    after update of end_date
    on exercises
    referencing new as ex
    for each row   
declare
    age         number(3);
    max_bpm     number(3);
    user_bday   profile.bday%type;
begin
    select bday
    into user_bday
    from profile
    where fit_user_id = :ex.fit_user_id;

    age := round((to_date(sysdate, 'YY-MM-DD') - user_bday)/365.25,0);
    max_bpm := 220 - age;

    if :ex.avg_bpm >= 0.76*max_bpm and :ex.avg_bpm <= 0.86*max_bpm
    then
        create_notice (:ex.ex_id, :ex.fit_user_id, 'kinda alto mas meh', 'placeholder', 'placeholder');
    end if;

    if :ex.avg_bpm >= 0.87*max_bpm and :ex.avg_bpm < max_bpm
    then
        create_notice (:ex.ex_id, :ex.fit_user_id, 'oi isso não esta bom', 'placeholder', 'placeholder');
    end if;

    if :ex.avg_bpm >= max_bpm
    then
        create_notice (:ex.ex_id, :ex.fit_user_id, 'vai para o hospital rapido', 'placeholder', 'placeholder');
    end if;
end;

create or replace NONEDITIONABLE trigger update_daily_status_trg
    after update of end_date
    on exercises
    referencing new as ex
    for each row   
declare
    is_completed daily_status.completed%type;
    has_daily    daily_status.completed%type;
    ex_end_date  daily_status.status_date%type;
    new_distance daily_status.distance%type;
    new_calories daily_status.calories%type;
    new_steps    daily_status.steps%type;
    goal_cals    daily_goals.daily_cals%type;
    goal_steps   daily_goals.daily_steps%type;
begin
    select sysdate 
    into ex_end_date
    from dual;

    select case
        when exists(
            select * 
            from DAILY_STATUS 
            where 
                fit_user_id = :ex.fit_user_id 
                and to_date(status_date,'YYYY-MM-DD') = to_date(ex_end_date,'YYYY-MM-DD')
        )
        then 1
        else 0
        end into has_daily
    from dual;

    if has_daily = 0
    then
        create_daily_status(:ex.fit_user_id);
    end if;

    select
        daily_steps,
        daily_cals
    into
        goal_steps,
        goal_cals
    from DAILY_GOALS
    where 
        fit_user_id = :ex.fit_user_id;

    select
        distance,
        calories,
        steps,
        completed
    into
        new_distance,
        new_calories,
        new_steps,
        is_completed
    from DAILY_STATUS
    where 
        fit_user_id = :ex.fit_user_id 
        and to_date(status_date,'YYYY-MM-DD') = to_date(ex_end_date,'YYYY-MM-DD');

    new_distance := new_distance + :ex.distance;
    new_calories := new_calories + :ex.calories;
    new_steps := new_steps + :ex.steps;

    if is_completed = 0  and (goal_steps != 0 or goal_cals != 0)
    then
        if new_steps >= goal_steps and new_calories >= goal_cals
        then
            is_completed := 1;
        end if;
    end if;

    update DAILY_STATUS set
        distance = new_distance,
        calories = new_calories,
        steps = new_steps,
        completed = is_completed
    where 
        fit_user_id = :ex.fit_user_id 
        and to_date(status_date,'YYYY-MM-DD') = to_date(ex_end_date,'YYYY-MM-DD');
end;

create or replace NONEDITIONABLE trigger update_daily_weight_trg
    after update of weight
    on profile
    referencing new as profile
    for each row   
declare
    
begin
    update DAILY_STATUS set
        weight = :profile.weight
    where 
        fit_user_id = :profile.fit_user_id and status_date = (select sysdate from dual);
end;

create or replace NONEDITIONABLE trigger update_totals_trg
    after update of end_date
    on exercises
    referencing new as ex
    for each row   
begin
    update TOTALS set
        distance = distance + :ex.distance,
        calories = calories + :ex.calories
    where 
        fit_user_id = :ex.fit_user_id 
        and activities_template_id = :ex.activities_template_id;
end;

create or replace NONEDITIONABLE trigger update_user_activity_trg
    after update of active
    on fit_user
    referencing new as new old as old
    for each row  
declare
    exp_date         transaction.t_date%type;
    transaction_date transaction.t_date%type;
    ifit_user_id     fit_user.id%type;
    user_premium     profile.premium%type;
begin
    if :new.active = 1 and :old.active = 0
    then
        create_user_activity(:new.id);
    else
        if :new.active = 0 and :old.active = 1
        then
            update user_activity 
            set end_date = (SELECT SYSTIMESTAMP FROM dual)
            where fit_user_id = :new.id
            and end_date is null;
        end if;
    end if;

    select 
        fit_user_id,
        premium
    into
        ifit_user_id,
        user_premium
    from profile
    where fit_user_id = :new.id;

    select max(t_date)
    into transaction_date
    from ( 
        select tr_id, t_date 
        from transaction
        where fit_user_id = ifit_user_id
    );

    if user_premium = 1
    then
        exp_date := ADD_MONTHS(transaction_date, 1);
        if to_date(exp_date,'YY-MM-DD') <= to_date(sysdate,'YY-MM-DD')
        then
            update profile
            set premium = 0
            where fit_user_id = ifit_user_id;
        end if;
    end if;
end;

create or replace NONEDITIONABLE trigger update_leaderboard_trg
    after update of end_date
    on exercises
    referencing new as ex
    for each row   
begin
    update_leaderboard (:ex.fit_user_id, :ex.activities_template_id);
end;

create or replace view daily_status_screen
    as
    select     
        daily_status.fit_user_id,
        profile.name,
        daily_status.daily_id,
        daily_status.status_date,  
        daily_status.distance,     
        daily_status.steps,        
        daily_status.weight,       
        daily_status.calories,     
        daily_status.completed
    from daily_status
        left join profile on profile.fit_user_id = daily_status.fit_user_id;
        
create or replace view friends_list_screen
    as
    select
        friends_list.fit_user_id,
        fit_user.username,
        profile.name
    from friends_list
        full outer join fit_user on fit_user.id = friends_list.fit_user_id1
        full outer join profile on profile.fit_user_id = fit_user.id
    where friends_list.accepted = 1;
    
create or replace view friends_request_screen
    as
    select
        friends_list.fit_user_id1,
        fit_user.username,
        profile.name
    from friends_list
        full outer join fit_user on fit_user.id = friends_list.fit_user_id
        full outer join profile on profile.fit_user_id = fit_user.id
    where friends_list.accepted is null;
    
create or replace view home_screen
    as
    select 
        profile.fit_user_id,
        profile.name, 
        daily_status.steps, 
        daily_goals.daily_steps, 
        profile.weight,
        exercises.duration, 
        exercises.distance, 
        exercises.calories, 
        exercises.begin_date
        from profile
        full outer join daily_status on daily_status.fit_user_id = profile.fit_user_id
        full outer join daily_goals on daily_goals.fit_user_id = daily_status.fit_user_id
        full outer join exercises on exercises.fit_user_id = daily_goals.fit_user_id
    where exercises.ex_id = (select max(ex_id) from exercises) or exercises.ex_id is null;
    
create or replace view nonactive_users
    as
    select
        fit_user.id,
        profile.name,
        fit_user.active,
        user_activity.begin_date, 
        user_activity.end_date
    from fit_user
        full outer join profile on profile.fit_user_id = fit_user.id
        full outer join user_activity on user_activity.fit_user_id = profile.fit_user_id
    where fit_user.active = 0
    order by fit_user.id, user_activity.end_date desc;
    
create or replace view notification_screen
    as
    select
        notice.fit_user_id,
        profile.name as user_name,
        activities_template.name,
        notice.date_hour,
        notice.title,
        notice.description
    from notice
        full outer join profile on profile.fit_user_id = notice.fit_user_id
        full outer join exercises on exercises.ex_id = notice.exercises_ex_id
        full outer join activities_template on activities_template.id = exercises.activities_template_id  
    where activities_template.id = (select activities_template_id from exercises where exercises.ex_id = notice.exercises_ex_id)
    order by notice.date_hour desc;
    
create or replace view recent_exercises_screen
    as
    select 
        exercises.fit_user_id,
        activities_template.name,
        exercises.begin_date,
        exercises.duration,
        exercises.steps,
        exercises.distance,
        exercises.calories
    from exercises
        left join activities_template on activities_template.id = exercises.activities_template_id
        order by begin_date desc;
        
create or replace view transactions_screen
    as
    select
        transaction.fit_user_id,
        profile.name, 
        transaction.tr_id,
        transaction.value,        
        transaction.t_date
    from transaction
        left join profile on profile.fit_user_id = transaction.fit_user_id
        order by transaction.t_date desc;
        
create or replace view user_activities_screen
    as
    select  
        user_activity.fit_user_id,
        profile.name,
        user_activity.act_date,   
        user_activity.begin_date, 
        user_activity.end_date,   
        user_activity.paid
    from user_activity
        left join profile on profile.fit_user_id = user_activity.fit_user_id;
        
create or replace view user_paid_screen
    as
    select 
        fit_user.id,
        profile.name,
        profile.premium
    from fit_user
        left join profile on profile.fit_user_id = fit_user.id
        order by profile.premium desc, fit_user.id;

-- Create users

call create_user ('Minecreeper', 'mde', 'gc.pombo@campus.fct.unl.pt', 'Guilherme', 61, 169, '2000-04-19', 'male');
call create_user ('Loukios', 'mde', 'Loukios@campus.fct.unl.pt', 'Loukios', 69, 175, '2000-01-01', 'male');
call create_user ('Duff', 'mde', 'Duff@campus.fct.unl.pt', 'Duff', 69, 175, '2000-01-01', 'male');
call create_user ('Constantin', 'mde', 'Constantin@campus.fct.unl.pt', 'Constantin', 69, 175, '2000-01-01', 'male');
call create_user ('Cirino', 'mde', 'Cirino@campus.fct.unl.pt', 'Cirino', 69, 175, '2000-01-01', 'male');
call create_user ('Yonah', 'mde', 'Yonah@campus.fct.unl.pt', 'Yonah', 69, 175, '2000-01-01', 'male');
call create_user ('Paora', 'mde', 'Paora@campus.fct.unl.pt', 'Paora', 69, 175, '2000-01-01', 'male');
call create_user ('Arttu', 'mde', 'Arttu@campus.fct.unl.pt', 'Arttu', 69, 175, '2000-01-01', 'male');
call create_user ('Eriu', 'mde', 'Eriu@campus.fct.unl.pt', 'Eriu', 69, 175, '2000-01-01', 'female');
call create_user ('Marlis', 'mde', 'Marlis@campus.fct.unl.pt', 'Marlis', 69, 175, '2000-01-01', 'female');
call create_user ('Meabh', 'mde', 'Meabh@campus.fct.unl.pt', 'Meabh', 69, 175, '2000-01-01', 'female');
call create_user ('Amabilia', 'mde', 'Amabilia@campus.fct.unl.pt', 'Amabilia', 69, 175, '2000-01-01', 'female');
call create_user ('Valkyrie', 'mde', 'Valkyrie@campus.fct.unl.pt', 'Valkyrie', 69, 175, '2000-01-01', 'female');
call create_user ('Drishti', 'mde', 'Drishti@campus.fct.unl.pt', 'Drishti', 69, 175, '2000-01-01', 'female');
call create_user ('Leanne', 'mde', 'Leanne@campus.fct.unl.pt', 'Leanne', 69, 175, '2000-01-01', 'female');
call create_user ('Sunitha', 'mde', 'Sunitha@campus.fct.unl.pt', 'Sunitha', 69, 175, '2000-01-01', 'female');
call create_user ('Tirta', 'mde', 'Tirta@campus.fct.unl.pt', 'Tirta', 69, 175, '2000-01-01', 'female');
call create_user ('Augusta', 'mde', 'Augusta@campus.fct.unl.pt', 'Augusta', 69, 175, '2000-01-01', 'female');
call create_user ('Katelyn', 'mde', 'Katelyn@campus.fct.unl.pt', 'Katelyn', 69, 175, '2000-01-01', 'female');
call create_user ('Nona', 'mde', 'Nona@campus.fct.unl.pt', 'Nona', 69, 175, '2000-01-01', 'female');
call create_user ('Aarti', 'mde', 'Aarti@campus.fct.unl.pt', 'Aarti', 69, 175, '2000-01-01', 'female');
call create_user ('Dominika', 'mde', 'Dominika@campus.fct.unl.pt', 'Dominika', 69, 175, '2000-01-01', 'female');
call create_user ('Helene', 'mde', 'Helene@campus.fct.unl.pt', 'Helene', 69, 175, '2000-01-01', 'female');
call create_user ('Danica', 'mde', 'Danica@campus.fct.unl.pt', 'Danica', 69, 175, '2000-01-01', 'female');
call create_user ('Italia', 'mde', 'Italia@campus.fct.unl.pt', 'Italia', 69, 175, '2000-01-01', 'female');
call create_user ('Laura', 'mde', 'Laura@campus.fct.unl.pt', 'Laura', 69, 175, '2000-01-01', 'female');
call create_user ('Narses', 'mde', 'Narses@campus.fct.unl.pt', 'Narses', 69, 175, '2000-01-01', 'male');
call create_user ('Colwyn', 'mde', 'Colwyn@campus.fct.unl.pt', 'Colwyn', 69, 175, '2000-01-01', 'male');
call create_user ('Suhail', 'mde', 'Suhail@campus.fct.unl.pt', 'Suhail', 69, 175, '2000-01-01', 'male');
call create_user ('Ajith', 'mde', 'Ajith@campus.fct.unl.pt', 'Ajith', 69, 175, '2000-01-01', 'male');
call create_user ('Buhle', 'mde', 'Buhle@campus.fct.unl.pt', 'Buhle', 69, 175, '2000-01-01', 'male');
call create_user ('Davit', 'mde', 'Davit@campus.fct.unl.pt', 'Davit', 69, 175, '2000-01-01', 'male');
call create_user ('Sander', 'mde', 'Sander@campus.fct.unl.pt', 'Sander', 69, 175, '2000-01-01', 'male');
call create_user ('Kumaran', 'mde', 'Kumaran@campus.fct.unl.pt', 'Kumaran', 69, 175, '2000-01-01', 'male');
call create_user ('Narayana', 'mde', 'Narayana@campus.fct.unl.pt', 'Narayana', 69, 175, '2000-01-01', 'male');

-- Update daily_goals

update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 1;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 2;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 3;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 4;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 5;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 6;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 7;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 8;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 9;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 10;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 11;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 12;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 13;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 14;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 15;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 16;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 17;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 18;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 19;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 20;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 21;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 22;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 23;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 24;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 25;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 26;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 27;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 28;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 29;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 30;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 31;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 32;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 33;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 34;
update daily_goals set daily_steps = 1000, daily_cals = 400 where fit_user_id = 35;

-- Create activities

call create_activities_template ('Squats', NULL, NULL, 8);
call create_activities_template ('Jumping Jacks', NULL, NULL, 16);
call create_activities_template ('Crab Walk', NULL, NULL, 10);
call create_activities_template ('Jogging', NULL, 60, NULL);
call create_activities_template ('Crunches', NULL, NULL, 6);
call create_activities_template ('Wall Pushups', NULL, NULL, 7);
call create_activities_template ('Lunges', NULL, NULL, 6);
call create_activities_template ('High Knees', NULL, NULL, 6);
call create_activities_template ('Wall Sit', NULL, NULL, TO_NUMBER('3.6', '9.99'));

-- Create friends

call create_friends ( 2, 7);
call create_friends ( 5, 4);
call create_friends ( 2, 26);
call create_friends ( 7, 3);
call create_friends ( 2, 5);
call create_friends ( 6, 16);
call create_friends ( 18, 21);
call create_friends ( 16, 1);
call create_friends ( 2, 1);
call create_friends ( 28, 1);
call create_friends ( 2, 12);
call create_friends ( 4, 3);
call create_friends ( 25, 6);
call create_friends ( 2, 8);
call create_friends ( 14, 19);
call create_friends ( 4, 17);
call create_friends ( 6, 23);
call create_friends ( 24, 12);
call create_friends ( 16, 11);

-- Create accept all invitations

call update_friends ( 7, 2);
call update_friends ( 4, 5);
call update_friends ( 26, 2);
call update_friends ( 3, 7);
call update_friends ( 5, 2);
call update_friends ( 16, 6);
call update_friends ( 21, 18);
call update_friends ( 1, 16);
call update_friends ( 1, 2);
call update_friends ( 1, 28);
call update_friends ( 12, 2);
call update_friends ( 3, 4);
call update_friends ( 6, 25);
call update_friends ( 8, 2);
call update_friends ( 19, 14);
call update_friends ( 17, 4);
call update_friends ( 23, 6);
call update_friends ( 12, 24);
call update_friends ( 11, 16);

-- Start exercises

call create_exercises(4,1);
call create_exercises(4,28);
call create_exercises(3,4);
call create_exercises(4,12);
call create_exercises(9,5);
call create_exercises(4,13);
call create_exercises(5,7);
call create_exercises(4,14);
call create_exercises(4,8);
call create_exercises(4,15);
call create_exercises(7,9);
call create_exercises(6,17);
call create_exercises(5,10);
call create_exercises(4,18);
call create_exercises(4,11);
call create_exercises(4,21);

-- Finish exercises

call update_exercises(1,23,0,159);
call update_exercises(28,10,0,153);
call update_exercises(4,0,0,132);
call update_exercises(12,20,0,179);
call update_exercises(5,0,0,139);
call update_exercises(13,30,0,146);
call update_exercises(7,0,0,179);
call update_exercises(14,40,0,145);
call update_exercises(8,20,0,146);
call update_exercises(15,30,0,179);
call update_exercises(9,0,0,211);
call update_exercises(17,0,0,146);
call update_exercises(10,0,0,132);
call update_exercises(18,10,0,146);
call update_exercises(11,15,0,153);
call update_exercises(21,50,0,153);

-- Online/offline and transactions

update fit_user set active = 1 where id = 1;
call create_transactions (1, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 1;
update fit_user set active = 0 where id = 1;
update fit_user set active = 1 where id = 2;
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 2;
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
call create_transactions (2, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 2;
update fit_user set active = 1 where id = 3;
call create_transactions (3, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 3;
call create_transactions (3, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 3;
update fit_user set active = 1 where id = 4;
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 4;
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
call create_transactions (4, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 4;
update fit_user set active = 1 where id = 5;
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 5;
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
call create_transactions (5, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 5;
update fit_user set active = 1 where id = 6;
call create_transactions (6, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 6;
call create_transactions (6, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 6;
update fit_user set active = 1 where id = 7;
call create_transactions (7, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 7;
update fit_user set active = 0 where id = 7;
update fit_user set active = 1 where id = 8;
call create_transactions (8, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 8;
call create_transactions (8, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 8;
update fit_user set active = 1 where id = 9;
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 9;
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
call create_transactions (9, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 9;
update fit_user set active = 1 where id = 10;
call create_transactions (10, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 10;
call create_transactions (10, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 10;
update fit_user set active = 1 where id = 11;
call create_transactions (11, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 11;
update fit_user set active = 0 where id = 11;
update fit_user set active = 1 where id = 12;
call create_transactions (12, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 12;
call create_transactions (12, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 12;
update fit_user set active = 1 where id = 13;
call create_transactions (13, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 13;
call create_transactions (13, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 13;
update fit_user set active = 1 where id = 14;
call create_transactions (14, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 14;
update fit_user set active = 0 where id = 14;
update fit_user set active = 1 where id = 15;
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 15;
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
call create_transactions (15, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 15;
update fit_user set active = 1 where id = 16;
call create_transactions (16, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 16;
update fit_user set active = 0 where id = 16;
update fit_user set active = 1 where id = 17;
call create_transactions (17, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 17;
call create_transactions (17, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 17;
update fit_user set active = 1 where id = 18;
call create_transactions (18, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 18;
update fit_user set active = 0 where id = 18;
update fit_user set active = 1 where id = 19;
call create_transactions (19, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 19;
update fit_user set active = 0 where id = 19;
update fit_user set active = 1 where id = 20;
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 20;
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
call create_transactions (20, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 20;
update fit_user set active = 1 where id = 21;
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 21;
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
call create_transactions (21, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 21;
update fit_user set active = 1 where id = 22;
call create_transactions (22, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 22;
call create_transactions (22, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 22;
update fit_user set active = 1 where id = 23;
call create_transactions (23, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 23;
update fit_user set active = 0 where id = 23;
update fit_user set active = 1 where id = 24;
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 24;
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
call create_transactions (24, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 24;
update fit_user set active = 1 where id = 25;
call create_transactions (25, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 25;
call create_transactions (25, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 25;
update fit_user set active = 1 where id = 26;
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 26;
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
call create_transactions (26, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 26;
update fit_user set active = 1 where id = 27;
call create_transactions (27, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 27;
call create_transactions (27, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 27;
update fit_user set active = 1 where id = 28;
call create_transactions (28, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 28;
call create_transactions (28, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 28;
update fit_user set active = 1 where id = 29;
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 29;
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
call create_transactions (29, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 29;
update fit_user set active = 1 where id = 30;
call create_transactions (30, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 30;
update fit_user set active = 0 where id = 30;
update fit_user set active = 1 where id = 31;
call create_transactions (31, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 31;
call create_transactions (31, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 31;
update fit_user set active = 1 where id = 32;
call create_transactions (32, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 32;
update fit_user set active = 0 where id = 32;
update fit_user set active = 1 where id = 33;
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 33;
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
call create_transactions (33, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 33;
update fit_user set active = 1 where id = 34;
call create_transactions (34, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 34;
call create_transactions (34, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 34;
update fit_user set active = 1 where id = 35;
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
update profile set premium = 1 where fit_user_id = 35;
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
call create_transactions (35, TO_NUMBER('0.99', '9.99'));
update fit_user set active = 0 where id = 35;

-- Update leaderboards

call update_leaderboard(1,4);
call update_leaderboard(28,4);
call update_leaderboard(4,3);
call update_leaderboard(12,4);
call update_leaderboard(5,9);
call update_leaderboard(13,4);
call update_leaderboard(7,5);
call update_leaderboard(14,4);
call update_leaderboard(8,4);
call update_leaderboard(15,4);
call update_leaderboard(9,7);
call update_leaderboard(17,6);
call update_leaderboard(10,5);
call update_leaderboard(18,4);
call update_leaderboard(11,4);
call update_leaderboard(21,4);

