-- SELECT 'DROP TABLE "' || TABLE_NAME || '" CASCADE CONSTRAINTS;' FROM user_tables;

DROP TABLE "FRIENDS_LIST" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "PROFILE" CASCADE CONSTRAINTS;
DROP TABLE "TOTALS" CASCADE CONSTRAINTS;
DROP TABLE "TRANSACTION" CASCADE CONSTRAINTS;
DROP TABLE "USER_ACTIVITY" CASCADE CONSTRAINTS;
DROP TABLE "ACTIVITIES_TEMPLATE" CASCADE CONSTRAINTS;
DROP TABLE "DAILY_GOALS" CASCADE CONSTRAINTS;
DROP TABLE "DAILY_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "EXERCISES" CASCADE CONSTRAINTS;
DROP TABLE "FIT_USER" CASCADE CONSTRAINTS;
DROP TABLE "FRIENDS_LEADERBOARD" CASCADE CONSTRAINTS;